authen/urls.py
from django.urls import path
from . import views

app_name = 'authen'

urlpatterns = [
    path('cadastro', views.cadastro_view, name="cadastro"),
    path('cadastro/create', views.cadastro_create, name="cadastro_create"),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name="home"),
    path('core/resultados', views.resultados, name="resultados"),
    path('core/detalhes', views.detalhes, name="detalhes"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('authen/', include('authen.urls', namespace='authen'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authen/models.py
from django.db import models

core/models.py
from django.db import models


class Veiculo(models.Model):

    class CambioVeiculo(models.TextChoices):
        MANUAL = 'M',
        AUTOMATICO = 'A',

    class TipoVeiculo(models.TextChoices):
        CARRO = "C",
        MOTO = "M",

    modelo = models.CharField(max_length=45)
    marca = models.CharField(max_length=15)
    placa = models.CharField(max_length=7)
    renavam = models.CharField(max_length=20)
    capacidade = models.PositiveIntegerField()
    combustivel = models.CharField(max_length=45)
    potencia = models.CharField(max_length=45)
    cor = models.CharField(max_length=12)
    ano = models.CharField(max_length=4)
    ar_condicionado = models.BooleanField(null=False, default=True)
    CD_DVD = models.BooleanField(null=False, default=True)
    disponivel = models.BooleanField(default=False)
    valor = models.DecimalField(max_digits=5, decimal_places=2)
    cambio = models.CharField(max_length=1, choices=CambioVeiculo.choices) # noqa
    tipo = models.CharField(max_length=1, choices=TipoVeiculo.choices, null=False) # noqa
    cover = models.ImageField(upload_to='core/covers/%Y/%m/%d/', blank=False)

    def __str__(self):
        return self.marca + ' ' + self.modelo

    class Meta:
        db_table = "Veiculo"
        verbose_name = "Veiculos"
        verbose_name_plural = "Veiculos"

authen/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    username = forms.CharField(
        label='Username',
        error_messages={
            'required': 'This field must not be empty',
            'min_length': 'Username must have at least 4 characters',
            'max_length': 'Username must have less than 150 characters',
        },
        min_length=4, max_length=150,

    )
    first_name = forms.CharField(
        error_messages={'required': 'Write your first name'},
        label='First name'
    )
    last_name = forms.CharField(
        error_messages={'required': 'Write your last name'},
        label='Last name',
    )
    email = forms.EmailField(
        error_messages={'required': 'E-mail is required'},
        label='E-mail',
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        error_messages={
            'required': 'Password must not be empty'
        },
        label='Password'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Password2',
        error_messages={
            'required': 'Please, repeat your password'
        },
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

authen/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import RegisterForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def cadastro_view(request):
    formulario_dados = request.session.get('formulario_dados', None)
    form = RegisterForm(formulario_dados)
    return render(request, 'authen/pages/cadastro.html', {
        'form': form,
        'form_action': reverse('authen:cadastro_create'),
    })


def cadastro_create(request):
    if not request.POST:
        raise Http404()
    POST = request.POST
    request.session['formulario_dados'] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()

        del (request.session['formulario_dados'])

    return redirect('authen:cadastro')


def login_view(request):
    form = LoginForm()
    return render(request, 'authen/pages/login.html', {
        'form': form,
        'form_action': reverse('authen:login_create')
    })


def login_create(request):
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)
    login_url = reverse('authen:login')

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', '')
        )
        if authenticated_user is not None:
            login(request, authenticated_user)

    return redirect(login_url)


@login_required(login_url='authen:login', redirect_field_name='next')
def logout_view(request):

    if not request.POST:
        return redirect(reverse('authen:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('authen:login'))

    logout(request)
    return redirect(reverse('authen:login'))

core/views.py
from django.shortcuts import render
from .models import Veiculo


def home(request):
    return render(request, 'space/pages/home.html')


def resultados(request):
    veiculos = Veiculo.objects.filter(disponivel=True).order_by('-id')
    return render(request, 'space/pages/resultados.html', context={
        'veiculos': veiculos,
    })


def detalhes(request):
    return render(request, 'space/pages/detalhes.html')

authen/templates/authen/pages/cadastro.html
{% extends 'global/base.html' %}
{% block title %}Cadastro{% endblock title %}
{% block content %}
<style>
.cadastro-content
{
    margin-top: 200px;
    background-color: rgba(12, 12, 17, 0.338);
    height:700px;
    flex-direction:column;
    width: 400px;
    border-radius: 8px;
}
.form-content
{
    font-size: 20px;
    display: flex;
    justify-content: center;
    flex-direction: column;
    width: 350px;
    font-weight: bold;
    color: rgba(255, 255, 255, 0.509);
}
.grande
{
    font-size: 40px;
    margin-top: 20px;
    margin-bottom: 20px;
    color: white;
}
input
{
    margin-top: 10px;
    margin-bottom: 20px;
    height:  30px;
    border-radius: 8px;
    color: black;
    font-size: 18px;
    align-items: center;
}
.enviar
{
    width: 100px;
    align-items: center;
}

</style>
<div class="cadastro-content">
    <center><h2 class="grande">CADASTRE-SE</h2>
        <hr>
    <div class="form-content">
    <form class="form-content"  action="{{form_action}}" method="POST"> 
        {% csrf_token %}
        {{ form }}
        <input class="enviar" type="submit">
    </form>
    </div></center>
</div>
{% endblock content %}

authen/templates/authen/pages/login.html
{% extends 'global/base.html' %}
{% block title %}Login{% endblock title %}
{% block interno %}
<style type="text/css">
  body
  {
    color: white;
  }
  input
  {
    height: 10%;
    text-align:center ;
    margin-top: 10px;
    margin-bottom: 20px;
    margin: 20px;
    height:  30px;
    border-radius: 8px;
    color: black;
    font-size: 18px;
    align-items: center;
    text-align: center;
   
  }
  .grande
  {
    font-size: 1cm;
  }
  .grande2
  {
    font-size: 20px;
  }
  .reserve-container
  {
    width: 700px;
    background-color: rgba(12, 12, 17, 0.338);
    display: flex;
    transform: scale(0.95) ;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    border-radius: 8px;
    
  }
  .inline-form
  {
    margin-top:70px;
    text-align: center;
    transform: scale3d(1.5);
    height: 4cm;
    font-size: 20px;
    justify-content: center;
  }
  .topo
  {
    font-size: 2cm;
  }
 

</style>
{% endblock interno %}
{% block content %}

 <center><div class="reserve-container">
    <h2 class="topo">Olá</h2>
    {% if request.user.is_authenticated %}
       <p class="grande">
          Você está logado como
          {{ request.user.username }}.
          <form class="inline-form" action="{% url 'authen:logout' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{ request.user.username }}" name="username">
            <button class="plaintext-button" type="submit"> <p class="grande2">Clique aqui para sair</p></button>
          </form> </p></center>

    {% endif %}
    <form action="{{ form_action }}" method="POST"> {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
  </div>
{% endblock content %}

core/templates/space/pages/detalhes.html
{% extends 'global/base.html' %}
{% block title %}Detalhes{% endblock title %}
{% block interno %}
<!--CSS Interno-->
<style type="text/css">
/*Caixa Central*/
.detalhes-container{
    width: 75%;
    height: 75%;
    display: flex;
    gap: 25px;
}
/*Caixa Esquerda*/
.detalhes-veiculo{
    width: 30%;
    height: 100%;
    background-color: white;
    border-radius: 2%;
    display: flex;
    flex-direction: column;
    align-items: center; 
}
.detalhes-reserva{
    width: 70%;
    height: 100%;
    background-color: white;
    border-radius: 2%;
    display: flex;
    flex-direction: column;
    align-items: center;
}
.detalhes-reserva > h2{
    margin: 15px;
}
.card-img{
    margin-top: -32px;
}
.card-img img {
    width: 100%;
    height: 100%;
    border-radius: 1em;
}
.desc{
    width: 80%;
}
.descrição{
    display: flex;
    margin: 25px;
    padding: 10px;
    gap: 10px;
    border-bottom: 1px solid  rgb(206, 206, 206);
    font-size: 25px;
    justify-content: center;
}
.centro{
    width: 100%;
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
}
.centro-block{
    width: 80%;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    margin: 10px;
    gap: 10px;
}
.black{
    width: 100%;
    display: flex;
    justify-content: center;
    padding: 10px;
    background-color: black;
    color: white;
    border-radius: 2%;
}
/*Total*/
.card-baixo{
    width: 100%;
    display: flex;
    justify-content: center;
    gap: 20px;
    margin-top: 100px;
}
.card-total{
    width: 50%;
    display: flex;
    justify-content: center;
    gap: 20px;
    padding: 20px;
    border: 2px dotted black;
    border-radius: 4%;
}
.card-total > p{
    border-right: 1px solid  rgb(32, 29, 29);
    padding-right: 10px;
}
.button{
    border: none;
    font-size: 16px;
    color: #FFF;
    padding: 14px;
    background-color: #000000;
    border-radius: 6px;
    margin: 15px;
    cursor: pointer;
    transition: all 0.3s ease;
}
.button:hover{
    background: #265DF2;
}

</style>
{% endblock interno %}
{% block content %}

    <div class="detalhes-container">
        <div class="detalhes-veiculo">
            <div class="card-img"> <img src="static/img/cars/m3-competition.png" alt="card image"> </div>
            <h2>White BMW</h2>
            <div class="desc">
                <div class="descrição">
                    <i class="fa-solid fa-snowflake" style="color: #006eff;"></i>
                    <p>Automático</p>
                </div>
                <div class="descrição">
                    <i class="fas fa-user" style="color: #006eff;"></i>
                    <p>5 Pessoas</p>
                </div>
                <div class="descrição">
                    <i class="fa-solid fa-snowflake" style="color: #006eff;"></i>
                    <p>Ar Condicionado</p>
                </div>
                <div class="descrição">
                    <i class="fas fa-user" style="color: #006eff;"></i>
                    <p>Air Bag</p>
                </div>
            </div>
        </div>
        <div class="detalhes-reserva">
            <h2>Resumo da Reserva</h2>
            <div class="centro">
                <div class="centro-block">
                    <div class="black"><h3>Retirada</h3> </div>
                    <p><strong> 30 de Junho de 2023 às 08:00</strong></p>
                    <p> Aeroporto Internac - Natal</p>
                </div>
                <div class="centro-block">
                    <div class="black"><h3>Devolução</h3> </div>
                    <p><strong> 30 de Junho de 2023 às 08:00</strong></p>
                    <p> Aeroporto Internac - Natal</p>
                </div>
            </div>
            <div class="card-baixo"> 
                <div class="card-total">
                    <p>Diaria<br> Total 1 x R$ 130,00</p>
                    <p>Proteção do Carro<br> 1 diaria x R$ 29,90</p>
                    <h3>Total:<br> R$ 159,90</h3>
                </div>
                <button class="button"> Confirmar </button>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/space/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="reserve-container">
        <div class="reserve-details">
            <form action="">
                <div class="radios-type">
                    <p>Que tipo de veículo está procurando?</p> 
                        <div class="radio-veiculo">
                            <input type="radio" name="tipo-veiculo" id="carro" value="C" required/>
                            <label for="carro">Carro</label>
                        </div>
                        <div class="radio-veiculo">
                            <input type="radio" name="tipo-veiculo" id="moto" value="M" required/>
                            <label for="moto">Moto</label>
                        </div>
                </div>
                <div class="local-rental">
                    <label for="cidade">Selecione o local de retirada do veículo</label>
                    <select name="cidade" id="cidade">
                        <option value="Canguaretama">Canguaretama</option>
                        <option value="Goianinha">Goianinha</option>
                        <option value="Montanhas">Montanhas</option>
                        <option value="Pipa">Pipa</option>
                        <option value="Natal">Parnamirim</option>
                        <option value="Natal">Natal</option>
                        <option value="Natal">Ceará-Mirim</option>
                    </select>
                    <label for="cidade">Selecione o local de devolução do veículo</label>
                    <select name="cidade" id="cidade">
                        <option value="Canguaretama">Canguaretama</option>
                        <option value="Goianinha">Goianinha</option>
                        <option value="Montanhas">Montanhas</option>
                        <option value="Pipa">Pipa</option>
                        <option value="Natal">Parnamirim</option>
                        <option value="Natal">Natal</option>
                        <option value="Natal">Ceará-Mirim</option>
                    </select>
                </div>
                <div class="times-loca">
                    <div class="tempo-retirada">
                        <div class="inputs-data-retirada">
                            <label for="data-retirada">Data de retirada do veículo</label>
                            <input type="date" name="data-retirada" id="dt-retirada" required/>
                        </div>
                        <div class="inputs-hora-retirada">
                            <label for="hora-retirada">Hora de retirada</label>
                            <input type="time" name="hora-retirada" id="hr-retirada" required/>
                        </div>
                    </div>
                    <div class="tempo-devolucao">
                        <div class="inputs-data-devolucao">
                            <label for="data-devolucao">Data de devolução do veículo</label>
                            <input type="date" name="data-devolucao" id="dt-devolucao" required/>
                        </div>
                        <div class="inputs-hora-devolucao">
                            <label for="hora-devolucao">Hora de devolução</label>
                            <input type="time" name="hora-devolucao" id="hr-devolucao" required/>
                        </div>
                    </div>
                </div>
                <div class="botao">
                    <button class="pesquisa">Pesquisar</button>
                </div>
            </form>
        </div>
        <div class="box-cards">
            <div class="card">
                <figure>
                    <img src="static/img/cards/card-car.png" alt="" width="95%" height="95%">
                </figure>
                <div class="header-card">
                    <h2>Carros Urbanos</h2>
                </div>
                <div class="card-text">
                    <p>Carros urbanos, compactos e eficientes em termos de combustível. Experimente a nova era da condução urbana.</p>
                </div>
            </div>
            <div class="card">
                <figure>
                    <img src="static/img/cards/card-moto.png" alt="" width="85%" height="95%">
                </figure>
                <div class="header-card">
                    <h2>2 rodas</h2>
                </div>
                <div class="card-text">
                    <p>Desfrute da liberdade de pilotar uma moto de qualidade e aproveite cada momento da sua jornada.</p>
                </div>
            </div>
            <div class="card">
                <figure>
                    <img src="static/img/cards/locacao.png" alt="" width="95%" height="105%">
                </figure>
                <div class="header-card">
                    <h2>Entrega e retirada</h2>
                </div>
                <div class="card-text">
                    <p>Oferecemos a comodidade de entregar e receber o veículo no local de sua escolha, como aeroportos, hotéis ou residências.</p>
                </div>
            </div>
</div>
{% endblock content %}

core/templates/space/pages/resultados.html
{% extends 'global/base.html' %}
{% block title %}Resultados{% endblock title %}
{% block interno %}
<!--CSS Interno-->
<style type="text/css">
  
.swiper-wrapper{
    width: 100%;
    height: 35em;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 30px;
}
.card{
    width: 20em;
    height: 90%;
    display: flex;
    flex-direction: column;
    align-items: center;
    background-color: #FFF;
    border-radius: 1em;
    box-shadow: 0 0 2em rgba(0, 0, 0, .2);
    padding: 2em 1em;
    margin: 0 1em;
}

.card-img{
    width: 20em;
    height: 15em;
    margin-top: -32px;
    
}
.card-img img {
    width: 100%;
    height: 100%;
    border-radius: 1em;
}
.card-content{
    display: flex;
    align-items: center;
    flex-direction: column;
}
.name{
    font-size: 1.5rem;
    font-weight: 500;
    position: relative;
    top: .2em;
    color: #333;
    padding: 10px;
}
.description{
    font-size: 1.1rem;
    text-align: center;
    margin: 1em 0;
    color: #707070;
    
}
.button{
    border: none;
    font-size: 16px;
    color: #FFF;
    padding: 8px 16px;
    background-color: #000000;
    border-radius: 6px;
    margin: 14px;
    cursor: pointer;
    transition: all 0.3s ease;
}
.button:hover{
    background: #265DF2;
}
</style>
{% endblock interno %}
{% block content %}
  <div class="container">
    <div class="results">
      <section class="swiper mySwiper">
        <div class="swiper-wrapper">
            {% for veiculo in veiculos %}
              {% include 'space/partials/veiculo.html' %}
            {% empty %}
              <div class="center">
                  <h1>Nenhum veículo encontrado</h1>
              </div>
            {% endfor %}
        </div>
      </section>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
  <script>
  var swiper = new Swiper(".mySwiper", {
    slidesPerView: 3,
    spaceBetween: 30,
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
    },
  });
  </script>

{% endblock content %}

core/templates/space/partials/footer.html
<footer>
    <div class="footer-content">
        <div class="footer-list">
            <ul>
                <li><h2>ACESSO CLIENTE</h2></li>
                <li><p>Consulte suas Reservas</p></li>
                <li><p>Acesse sua Conta</p></li>
                <li><p>Cadastre-se</p></li>
            </ul>
            <ul>
                <li><h2>ATENDIMENTO AO CLIENTE</h2></li>
                <li><p>Dúvidas Frequentes</p></li>
                <li><p>Fale Conosco</p></li>
                <li><p>Alteração e Cancelamentos</p></li>
            </ul>
            <ul>
                <li><h2>SOBRE NÓS</h2></li>
                <li><p>IN9CAR</p></li>
                <li><p>Politica de Privacidade</p></li>
                <li><p>Termos e Condições</p></li>
                <li><p>Trabalhe Conosco</p></li>
            </ul>
        </div>
        <div class="footer-partners">
            <h2>Nossos parceiros:</h2>
            <figure>
                <img src="static/img/icons/bmw.png" alt="Logo da BMW" height="60px" width="60px">
                <img src="static/img/icons/chevrolet.png" alt="Logo da Chevrolet" height="60px" width="60px">
                <img src="static/img/icons/volkswagen.png" alt="Logo da Volkswagen" height="60px" width="60px">
            </figure>
        </div>
    </div>
    <div class="region-footer">
        <small>&copy; 2023 IN9CAR | - Nenhum direito reservado.</small>
    </div>
</footer>

core/templates/space/partials/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link rel="stylesheet" href="{% static 'space/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">

core/templates/space/partials/header.html
<header>
    <a href="{% url 'core:home' %}">    
        <div class="logotipo">
            <img src="static/img/carro.png" alt="Logotipo do site" width="65px" height="65px">
            <h1>IN9CAR</h1>
        </div>
    </a>
    <nav>
        <ul>
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="">Minhas reservas</a></li>
            <li><a href="">Suporte</a></li>
        </ul>
    </nav>
    <div class="box-user">
    <a href="">    
        <div>
            <a href="{% url 'authen:login' %}">Sign in</a>
        </div>
    </a>
    <a href="">
        <div class="box-cadastro">
            <a href="{% url 'authen:cadastro' %}"> Sign Up </a>
        </div>
    </a>
    </div>
</header>

core/templates/space/partials/veiculo.html
<div class="card swiper-slide">
  <div class="card-img">
      <img src="{{ veiculo.cover.url }}" alt="card image">
  </div>
  <div class="card-content">
      <span class="name">{{ veiculo.marca}} {{veiculo.modelo}}</span>
      <p class="description"> Combinando habilidades incomparáveis com um design sofisticado, esse veículo é perfeito para explorar novos horizontes. </p>
      <h2>${{veiculo.valor}}/dia</h2>
      <button class="button"> Saiba mais</button>
  </div>
</div>